"""add qbank source documents and ai generation tracking

Revision ID: 1236f0acdb88
Revises: 2fcffff2d69e
Create Date: 2026-08-12 04:54:17.528476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1236f0acdb88'
down_revision: Union[str, None] = '2fcffff2d69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qbank_source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.Enum('STCW', 'IMO', 'COMPANY_SOP', 'COURSE_MANUAL', 'OTHER', name='qbank_source_document_type'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qbank_source_documents_course_id'), 'qbank_source_documents', ['course_id'], unique=False)
    op.add_column('qbank_generation_batches', sa.Column('prompt_version', sa.String(length=20), nullable=True))
    op.add_column('qbank_generation_batches', sa.Column('source_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('qbank_generation_batches', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('qbank_generation_batches', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('qbank_generation_batches', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('qbank_questions', sa.Column('source_document_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'qbank_questions', 'qbank_source_documents', ['source_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('qbank_questions_source_document_id_fkey', 'qbank_questions', type_='foreignkey')
    op.drop_column('qbank_questions', 'source_document_id')
    op.drop_column('qbank_generation_batches', 'error_message')
    op.drop_column('qbank_generation_batches', 'output_tokens')
    op.drop_column('qbank_generation_batches', 'input_tokens')
    op.drop_column('qbank_generation_batches', 'source_document_ids')
    op.drop_column('qbank_generation_batches', 'prompt_version')
    op.drop_index(op.f('ix_qbank_source_documents_course_id'), table_name='qbank_source_documents')
    op.drop_table('qbank_source_documents')
    # ### end Alembic commands ###

    # نفس الملاحظة المتكررة: Alembic autogenerate لا يُسقط أنواع ENUM.
    bind = op.get_bind()
    bind.execute(sa.text("DROP TYPE IF EXISTS qbank_source_document_type"))
