"""add qbank question bank and exam engine tables

Revision ID: 2fcffff2d69e
Revises: d4674cf750b6
Create Date: 2026-08-11 15:51:03.885865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2fcffff2d69e'
down_revision: Union[str, None] = 'd4674cf750b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qbank_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qbank_tags_name'), 'qbank_tags', ['name'], unique=True)
    op.create_table('qbank_exam_blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('difficulty_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interaction_type_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_type_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competency_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passing_score_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qbank_learning_objectives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('competency_criteria_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_criteria_id'], ['competency_criteria.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'code', name='uq_lo_code_per_course')
    )
    op.create_table('qbank_exam_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('competency_assessment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'EXPIRED', 'VOIDED', name='qbank_exam_attempt_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['qbank_exam_blueprints.id'], ),
    sa.ForeignKeyConstraint(['competency_assessment_id'], ['competency_assessments.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qbank_exam_attempts_trainee_id'), 'qbank_exam_attempts', ['trainee_id'], unique=False)
    op.create_table('qbank_generation_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('learning_objective_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='qbank_generation_batch_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['learning_objective_id'], ['qbank_learning_objectives.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qbank_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('competency_criteria_id', sa.UUID(), nullable=True),
    sa.Column('learning_objective_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('generation_batch_id', sa.UUID(), nullable=True),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('interaction_type', sa.Enum('MCQ', 'TRUE_FALSE', 'MULTIPLE_RESPONSE', 'MATCHING', 'ORDERING', name='qbank_interaction_type'), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'IMAGE', 'AUDIO', 'TEXT_IMAGE', 'TEXT_AUDIO', 'IMAGE_AUDIO', name='qbank_content_type'), nullable=False),
    sa.Column('is_scenario_based', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='qbank_difficulty'), nullable=False),
    sa.Column('stem_text', sa.Text(), nullable=False),
    sa.Column('scenario_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'AI_GENERATED', 'AI_REVIEWED', 'HUMAN_REVIEW', 'APPROVED', 'PUBLISHED', 'REJECTED', 'RETIRED', name='qbank_question_status'), nullable=False),
    sa.Column('source_type', sa.Enum('AI_GENERATED', 'HUMAN_AUTHORED', 'IMPORTED', name='qbank_source_type'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_status', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('times_shown', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('discrimination_index', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['competency_criteria_id'], ['competency_criteria.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['qbank_questions.id'], ),
    sa.ForeignKeyConstraint(['generation_batch_id'], ['qbank_generation_batches.id'], ),
    sa.ForeignKeyConstraint(['learning_objective_id'], ['qbank_learning_objectives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', 'course_id', name='uq_qbank_question_hash_per_course')
    )
    op.create_index(op.f('ix_qbank_questions_competency_criteria_id'), 'qbank_questions', ['competency_criteria_id'], unique=False)
    op.create_index(op.f('ix_qbank_questions_content_hash'), 'qbank_questions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_qbank_questions_course_id'), 'qbank_questions', ['course_id'], unique=False)
    op.create_index(op.f('ix_qbank_questions_status'), 'qbank_questions', ['status'], unique=False)
    op.create_table('qbank_duplicate_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('candidate_duplicate_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('flag_type', sa.Enum('EXACT', 'NEAR_DUPLICATE', 'SIMILAR_SCENARIO', 'SIMILAR_ANSWER_SET', name='qbank_duplicate_flag_type'), nullable=False),
    sa.Column('resolution', sa.Enum('PENDING', 'CONFIRMED_DUPLICATE', 'CONFIRMED_DISTINCT', name='qbank_duplicate_resolution'), nullable=False),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_duplicate_id'], ['qbank_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['qbank_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qbank_exam_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('selected_option_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['qbank_exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['qbank_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_qbank_exam_question_per_attempt')
    )
    op.create_table('qbank_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('match_text', sa.Text(), nullable=True),
    sa.Column('order_position', sa.Integer(), nullable=True),
    sa.Column('is_distractor_quality_flagged', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['qbank_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qbank_question_tags',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['qbank_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['qbank_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'tag_id')
    )
    op.create_table('qbank_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.Enum('AI_AUTO', 'HUMAN', name='qbank_review_type'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'REQUEST_CHANGES', 'FLAG_DUPLICATE', name='qbank_review_decision'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['qbank_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qbank_trainee_question_history',
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('last_shown_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('times_shown', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['qbank_questions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('trainee_id', 'question_id')
    )
    op.create_table('qbank_media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('option_id', sa.UUID(), nullable=True),
    sa.Column('attach_point', sa.Enum('STEM', 'OPTION', 'EXPLANATION', 'SCENARIO', name='qbank_media_attach_point'), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'AUDIO', 'ATTACHMENT', name='qbank_media_type'), nullable=False),
    sa.Column('storage_provider', sa.Enum('S3', 'R2', 'LOCAL', name='qbank_storage_provider'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['qbank_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['qbank_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qbank_media_assets_checksum_sha256'), 'qbank_media_assets', ['checksum_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qbank_media_assets_checksum_sha256'), table_name='qbank_media_assets')
    op.drop_table('qbank_media_assets')
    op.drop_table('qbank_trainee_question_history')
    op.drop_table('qbank_reviews')
    op.drop_table('qbank_question_tags')
    op.drop_table('qbank_options')
    op.drop_table('qbank_exam_questions')
    op.drop_table('qbank_duplicate_flags')
    op.drop_index(op.f('ix_qbank_questions_status'), table_name='qbank_questions')
    op.drop_index(op.f('ix_qbank_questions_course_id'), table_name='qbank_questions')
    op.drop_index(op.f('ix_qbank_questions_content_hash'), table_name='qbank_questions')
    op.drop_index(op.f('ix_qbank_questions_competency_criteria_id'), table_name='qbank_questions')
    op.drop_table('qbank_questions')
    op.drop_table('qbank_generation_batches')
    op.drop_index(op.f('ix_qbank_exam_attempts_trainee_id'), table_name='qbank_exam_attempts')
    op.drop_table('qbank_exam_attempts')
    op.drop_table('qbank_learning_objectives')
    op.drop_table('qbank_exam_blueprints')
    op.drop_index(op.f('ix_qbank_tags_name'), table_name='qbank_tags')
    op.drop_table('qbank_tags')
    # ### end Alembic commands ###

    # ملاحظة: Alembic autogenerate لا يُسقط أنواع ENUM في PostgreSQL تلقائيًا
    # عند إسقاط الجداول التي تستخدمها — يجب إسقاطها صراحةً هنا يصاد \n    # upgrade لاحق بخطأ "type already exists". تم اكتشاف هذا فعليًا أثناء
    # اختبار downgrade/upgrade على قاعدة بيانات Postgres حقيقية في هذه المرحلة.
    bind = op.get_bind()
    for enum_name in (
        "qbank_content_type",
        "qbank_difficulty",
        "qbank_duplicate_flag_type",
        "qbank_duplicate_resolution",
        "qbank_exam_attempt_status",
        "qbank_generation_batch_status",
        "qbank_interaction_type",
        "qbank_media_attach_point",
        "qbank_media_type",
        "qbank_question_status",
        "qbank_review_decision",
        "qbank_review_type",
        "qbank_source_type",
        "qbank_storage_provider",
    ):
        bind.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
