"""add qbank generation jobs and tasks queue infrastructure

Revision ID: ab0b7df590a9
Revises: 1236f0acdb88
Create Date: 2026-08-17 20:30:13.059071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ab0b7df590a9'
down_revision: Union[str, None] = '1236f0acdb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qbank_generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('total_requested', sa.Integer(), nullable=False),
    sa.Column('total_generated', sa.Integer(), nullable=False),
    sa.Column('total_rejected', sa.Integer(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='qbank_generation_job_status'), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qbank_generation_jobs_course_id'), 'qbank_generation_jobs', ['course_id'], unique=False)
    op.create_table('qbank_generation_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('generation_batch_id', sa.UUID(), nullable=True),
    sa.Column('learning_objective_id', sa.UUID(), nullable=True),
    sa.Column('interaction_type', sa.String(length=30), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('is_scenario_based', sa.Boolean(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('source_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='qbank_generation_task_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_batch_id'], ['qbank_generation_batches.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['qbank_generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_objective_id'], ['qbank_learning_objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qbank_generation_tasks_job_id'), 'qbank_generation_tasks', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qbank_generation_tasks_job_id'), table_name='qbank_generation_tasks')
    op.drop_table('qbank_generation_tasks')
    op.drop_index(op.f('ix_qbank_generation_jobs_course_id'), table_name='qbank_generation_jobs')
    op.drop_table('qbank_generation_jobs')
    # ### end Alembic commands ###

    # نفس الملاحظة المتكررة: Alembic autogenerate لا يُسقط أنواع ENUM.
    bind = op.get_bind()
    for enum_name in ("qbank_generation_job_status", "qbank_generation_task_status"):
        bind.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
