"""baseline existing schema

Revision ID: d4674cf750b6
Revises: 
Create Date: 2026-08-11 15:50:18.451398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4674cf750b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stcw_reference', sa.String(length=100), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('validity_months', sa.Integer(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_table('organization_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('imo_number', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TRAINING_MANAGER', 'INSTRUCTOR', 'ASSESSOR', 'TRAINEE', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competency_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='course_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_code', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('national_id', sa.String(length=30), nullable=True),
    sa.Column('passport_number', sa.String(length=30), nullable=True),
    sa.Column('seaman_book_number', sa.String(length=30), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('organization_unit_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainees_national_id'), 'trainees', ['national_id'], unique=False)
    op.create_index(op.f('ix_trainees_trainee_code'), 'trainees', ['trainee_code'], unique=True)
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendance_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certificate_number', sa.String(length=60), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ISSUED', 'EXPIRED', 'REVOKED', 'PENDING', name='certificate_status'), nullable=False),
    sa.Column('file_reference', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_certificate_number'), 'certificates', ['certificate_number'], unique=True)
    op.create_table('competency_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('criteria_id', sa.UUID(), nullable=False),
    sa.Column('assessor_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('result', sa.Enum('COMPETENT', 'NOT_YET_COMPETENT', 'PENDING', name='assessment_result'), nullable=False),
    sa.Column('assessed_on', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['criteria_id'], ['competency_criteria.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'CONFIRMED', 'ATTENDING', 'COMPLETED', 'WITHDRAWN', 'FAILED', name='enrollment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('instructor_rating', sa.Integer(), nullable=False),
    sa.Column('content_rating', sa.Integer(), nullable=False),
    sa.Column('facilities_rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mci_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('calculated_on', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('attendance_component', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('competency_component', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('certification_component', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('recency_component', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mci_scores')
    op.drop_table('feedback_surveys')
    op.drop_table('enrollments')
    op.drop_table('competency_assessments')
    op.drop_index(op.f('ix_certificates_certificate_number'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_trainees_trainee_code'), table_name='trainees')
    op.drop_index(op.f('ix_trainees_national_id'), table_name='trainees')
    op.drop_table('trainees')
    op.drop_table('course_sessions')
    op.drop_table('competency_criteria')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organization_units')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###

    # نفس ملاحظة migration الـqbank: Alembic autogenerate لا يُسقط أنواع
    # ENUM في PostgreSQL تلقائيًا — يجب إسقاطها صراحةً هنا.
    bind = op.get_bind()
    for enum_name in (
        "user_role",
        "course_status",
        "attendance_status",
        "certificate_status",
        "assessment_result",
        "enrollment_status",
    ):
        bind.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
